(() => {
  "use strict";
  const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
  const S={token:sessionStorage.getItem("aureon_token"),user:null,tiers:[],prices:[],balances:[],investments:[],deposits:[],withdrawals:[],addresses:[]};
  const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]),n=(v,d=8)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:d}).format(Number(v||0)),usd=v=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(Number(v||0)),date=v=>v?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(v)):"—",tag=v=>`<span class="status ${esc(v)}">${esc(v)}</span>`,key=p=>`${p}-${crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random().toString(36).slice(2)}`;
  async function api(path,opt={}){const headers={...(opt.body?{"Content-Type":"application/json"}:{}),...(opt.headers||{})};if(S.token)headers.Authorization=`Bearer ${S.token}`;let r;try{r=await fetch(path,{...opt,headers})}catch(_){throw Error("Network connection unavailable. Please try again.")}const data=r.status===204?null:await r.json().catch(()=>null);if(!r.ok){if(r.status===401&&S.token)signOut();throw Error(data?.detail||"Something went wrong. Please try again.")}return data}
  function toast(m,type=""){const e=$("#toast");e.textContent=m;e.className=`toast ${type}`;clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add("hidden"),4200)}
  function alert(m=""){const e=$("#app-notice");e.textContent=m;e.classList.toggle("hidden",!m)}
  async function publicData(){try{[S.tiers,S.prices]=await Promise.all([api("/tiers"),api("/prices")]);tiers();prices();tierOptions()}catch(e){$("#public-prices").innerHTML=`<span class="muted">${esc(e.message)}</span>`}}
  function prices(){const marks={BTC:"₿",ETH:"Ξ",USDT:"₮"};$("#public-prices").innerHTML=S.prices.map(p=>`<div class="ticker-item"><span class="ticker-icon">${marks[p.asset]||"◈"}</span><span><strong>${esc(p.asset)} ${usd(p.usd_price)}</strong><small>${esc(p.source)} · ${date(p.updated_at)}</small></span></div>`).join("")||'<span class="muted">Prices temporarily unavailable.</span>'}
  function tiers(){$("#tier-cards").innerHTML=S.tiers.map((t,i)=>`<article class="tier-card ${i===1?"featured":""}"><div class="tier-top"><span>${esc(t.code)}</span>${i===1?'<b class="tier-badge">Popular</b>':""}</div><h3>${esc(t.display_name)}</h3><div class="tier-rate">${n(Number(t.annual_roi_rate)*100,2)}% <small>annual projection</small></div><p class="tier-range">${n(t.minimum,2)} — ${n(t.maximum,2)} USDT</p><div class="tier-details"><span>Referral bonus</span><b>${n(Number(t.referral_rate)*100,2)}%</b></div><button data-explore="${esc(t.code)}">Explore ${esc(t.display_name)} →</button></article>`).join("")||'<div class="loading-card">No active tiers right now.</div>'}
  function tierOptions(){const e=$("#roi-tier"),current=e.value;e.innerHTML=S.tiers.map(t=>`<option value="${esc(t.code)}">${esc(t.display_name)} · ${n(Number(t.annual_roi_rate)*100,2)}%</option>`).join("");if(current)e.value=current}
  function authTab(m){$$("[data-auth-tab]").forEach(x=>x.classList.toggle("active",x.dataset.authTab===m));$("#login-form").classList.toggle("hidden",m!=="login");$("#register-form").classList.toggle("hidden",m!=="register");$("#auth-error").textContent=""}
  function authOpen(m="login"){$("#auth-dialog").showModal();authTab(m)}
  async function auth(ev,register){ev.preventDefault();const data=Object.fromEntries(new FormData(ev.currentTarget));if(!data.referral_code)delete data.referral_code;try{if(register)await api("/auth/register",{method:"POST",body:JSON.stringify(data)});const login=await api("/auth/login",{method:"POST",body:JSON.stringify({email:data.email,password:data.password})});S.token=login.access_token;sessionStorage.setItem("aureon_token",S.token);$("#auth-dialog").close();await enter();toast(register?"Account created. Welcome to Aureon.":"Signed in successfully.")}catch(e){$("#auth-error").textContent=e.message}}
  async function enter(){try{S.user=await api("/me");document.body.classList.add("app-mode");$("#app-shell").classList.remove("hidden");$("#profile-email").textContent=S.user.email;$("#profile-initial").textContent=S.user.email[0].toUpperCase();$("#profile-role").textContent=S.user.role;$$(".admin-only").forEach(x=>x.classList.toggle("hidden",S.user.role!=="admin"));await refresh();view("dashboard")}catch(e){toast(e.message,"error");signOut()}}
  function signOut(){sessionStorage.removeItem("aureon_token");S.token=null;S.user=null;document.body.classList.remove("app-mode");$("#app-shell").classList.add("hidden");$(".sidebar").classList.remove("open");location.hash="home"}
  async function refresh(){if(!S.token)return;alert("");try{const [balances,investments,deposits,withdrawals,addresses,prices_,tiers_]=await Promise.all([api("/wallet/balances"),api("/investments"),api("/deposits"),api("/withdrawals"),api("/wallet/receiving-addresses"),api("/prices"),api("/tiers")]);Object.assign(S,{balances,investments,deposits,withdrawals,addresses,prices:prices_,tiers:tiers_});render();if(S.user?.role==="admin")await admin()}catch(e){alert(e.message)}}
  const bal=a=>S.balances.find(x=>x.asset===a)||{available:0,locked:0};
  function render(){prices();tierOptions();overview();positions();wallet()}
  function overview(){const u=bal("USDT"),active=S.investments.filter(i=>i.status==="active"),value=S.balances.reduce((s,b)=>s+Number(b.available)*Number(S.prices.find(p=>p.asset===b.asset)?.usd_price||0),0);$("#portfolio-value").textContent=usd(value);$("#portfolio-subtitle").textContent=`Market valuation of ${S.balances.length||0} available internal balance${S.balances.length===1?"":"s"}`;$("#referral-code").textContent=S.user?.referral_code||"—";$("#available-total").textContent=`${n(u.available,2)} USDT`;$("#locked-total").textContent=`${n(u.locked,2)} USDT`;$("#active-count").textContent=active.length;$("#price-age").textContent=S.prices[0]?`Updated ${date(S.prices[0].updated_at)}`:"No cached quote";$("#positions-list").innerHTML=active.length?active.map(i=>`<div class="position-row"><div class="row-title"><span class="asset-avatar">${esc(i.tier_code[0])}</span><span><strong>${esc(i.tier_code)} position</strong><small>Matures ${date(i.matures_at)} · ${i.term_days} days</small></span></div><div class="row-value"><strong>${n(i.principal,2)} USDT</strong><small>+${n(i.expected_roi,2)} projected</small></div></div>`).join(""):'<div class="list-empty">No active positions yet.</div>';$("#balance-list").innerHTML=S.balances.length?S.balances.map(b=>`<div class="balance-row"><div class="row-title"><span class="asset-avatar">${esc(b.asset)}</span><span><strong>${esc(b.asset)}</strong><small>Internal wallet balance</small></span></div><div class="row-value"><strong>${n(b.available)} available</strong><small>${n(b.locked)} locked</small></div></div>`).join(""):'<div class="list-empty">Approved deposits will appear here.</div>'}
  function positions(){$("#all-positions").innerHTML=S.investments.length?S.investments.map(i=>`<div class="position-row"><div class="row-title"><span class="asset-avatar">${esc(i.tier_code[0])}</span><span><strong>${esc(i.tier_code)} · ${n(i.principal,2)} USDT</strong><small>Created ${date(i.starts_at)} · Matures ${date(i.matures_at)}</small></span></div><div class="row-value">${tag(i.status)}${i.status==="active"?`<button class="small-button" data-settle="${i.id}">Settle if mature</button>`:`<small>ROI projection: ${n(i.expected_roi,2)} USDT</small>`}</div></div>`).join(""):'<div class="list-empty">No positions created.</div>'}
  function transfer(x,type){const detail=type==="deposit"?x.tx_hash:x.destination_address,time=type==="deposit"?x.submitted_at:x.requested_at;return `<div class="position-row"><div class="row-title"><span class="asset-avatar">${esc(x.asset)}</span><span><strong>${n(x.amount)} ${esc(x.asset)}</strong><small>${esc(x.network)} · ${esc(detail.slice(0,15))}… · ${date(time)}</small></span></div><div class="row-value">${tag(x.status)}<small>${esc(x.review_note||"Awaiting review")}</small></div></div>`}
  function wallet(){$("#wallet-summary").innerHTML=S.balances.length?S.balances.map(b=>`<article class="surface"><p class="eyebrow">${esc(b.asset)}</p><strong>${n(b.available)} <small>available</small></strong><p>${n(b.locked)} currently locked</p></article>`).join(""):'<article class="surface"><p class="eyebrow">Wallet</p><strong>No balances</strong><p>Submit a verified deposit to begin.</p></article>';$ ("#deposit-address").innerHTML=`<option value="">Select an approved address</option>${S.addresses.map(a=>`<option value="${a.id}">${esc(a.asset)} · ${esc(a.network)} · ${esc(a.address.slice(0,10))}…</option>`).join("")}`;address();$("#deposit-list").innerHTML=S.deposits.length?S.deposits.map(x=>transfer(x,"deposit")).join(""):'<div class="list-empty">No deposits submitted.</div>';$("#withdrawal-list").innerHTML=S.withdrawals.length?S.withdrawals.map(x=>transfer(x,"withdrawal")).join(""):'<div class="list-empty">No withdrawals requested.</div>'}
  function address(){const a=S.addresses.find(x=>x.id===$("#deposit-address").value);$("#address-preview").textContent=a?`${a.asset} on ${a.network}: ${a.address}`:"Select an address to review network details."}
  async function roi(ev){ev.preventDefault();const d=Object.fromEntries(new FormData($("#roi-form")));if(!d.tier_code||!d.amount)return toast("Choose a tier and enter an amount.","error");try{const q=await api("/roi/quote",{method:"POST",body:JSON.stringify({...d,term_days:Number(d.term_days)})});$("#roi-result").classList.remove("muted");$("#roi-result").innerHTML=`<span>Projected ROI over ${q.term_days} days at ${n(Number(q.annual_roi_rate)*100,2)}% annual rate</span><strong>${n(q.expected_roi,2)} USDT</strong><span>Projected total: <b>${n(q.projected_total,2)} USDT</b>. Projection only, not a guaranteed return.</span>`;const f=$("#investment-form");["tier_code","amount","term_days"].forEach(k=>f.elements[k].value=d[k])}catch(e){$("#roi-result").textContent=e.message}}
  async function invest(ev){ev.preventDefault();const d=Object.fromEntries(new FormData(ev.currentTarget));if(!d.amount)return toast("Calculate a projection before creating a position.","error");try{await api("/investments",{method:"POST",body:JSON.stringify({...d,term_days:Number(d.term_days),idempotency_key:key("investment")})});toast("Position created and principal moved to locked balance.");await refresh()}catch(e){toast(e.message,"error")}}
  async function submit(path,ev,more={}){ev.preventDefault();try{await api(path,{method:"POST",body:JSON.stringify({...Object.fromEntries(new FormData(ev.currentTarget)),...more})});ev.currentTarget.reset();toast(path==="/deposits"?"Deposit submitted for manual review.":"Withdrawal reserved and sent for review.");await refresh()}catch(e){toast(e.message,"error")}}
  async function settle(id){try{await api(`/investments/${id}/settle`,{method:"POST"});toast("Position settled to available USDT.");await refresh()}catch(e){toast(e.message,"error")}}
  async function activity(){const c=$("#ledger-list");c.innerHTML='<div class="list-empty">Loading activity…</div>';try{const rows=await api("/wallet/ledger?limit=100");c.innerHTML=rows.length?rows.map(r=>`<div class="ledger-row"><div><strong>${esc(r.event_type.replaceAll("_"," "))}</strong><small>${date(r.created_at)} · ${esc(r.reference_type)}</small></div><div class="row-value"><strong class="${Number(r.amount)>=0?"delta-positive":"delta-negative"}">${Number(r.amount)>=0?"+":""}${n(r.amount)} ${esc(r.asset)}</strong><small>Balance: ${n(r.balance_after)}</small></div></div>`).join(""):'<div class="list-empty">No activity yet.</div>'}catch(e){c.textContent=e.message}}
  async function admin(){try{const[d,deposits,withdrawals]=await Promise.all([api("/admin/dashboard"),api("/admin/deposits?review_status=pending"),api("/admin/withdrawals?review_status=pending")]);$("#admin-stats").innerHTML=[["Users",d.users,"Registered accounts"],["Active positions",d.active_investments,"Across all tiers"],["Pending deposits",d.pending_deposits,"Require validation"],["Pending withdrawals",d.pending_withdrawals,"Require external proof"]].map(x=>`<article><p>${x[0]}</p><strong>${n(x[1],0)}</strong><small>${x[2]}</small></article>`).join("");const review=(x,type)=>`<div class="review-row"><div class="row-title"><span class="asset-avatar">${esc(x.asset)}</span><span><strong>${n(x.amount)} ${esc(x.asset)} · ${esc(x.network)}</strong><small>${esc(type==="deposit"?x.tx_hash:x.destination_address)}<br />Submitted ${date(type==="deposit"?x.submitted_at:x.requested_at)}</small></span></div><div class="review-actions"><button class="small-button approve" data-review="${type}|${x.id}|yes">${type==="withdrawal"?"Approve + hash":"Approve"}</button><button class="small-button reject" data-review="${type}|${x.id}|no">Reject</button></div></div>`;$("#admin-deposits").innerHTML=deposits.length?deposits.map(x=>review(x,"deposit")).join(""):'<div class="list-empty">No pending deposits.</div>';$("#admin-withdrawals").innerHTML=withdrawals.length?withdrawals.map(x=>review(x,"withdrawal")).join(""):'<div class="list-empty">No pending withdrawals.</div>';$("#admin-wallets").innerHTML=S.addresses.length?S.addresses.map(a=>`<div class="mini-row"><span><strong>${esc(a.asset)} · ${esc(a.network)}</strong><small>${esc(a.address)}</small></span><button class="small-button reject" data-disable="${a.id}">Disable</button></div>`).join(""):'<div class="list-empty">No active addresses.</div>';$("#admin-tiers").innerHTML=S.tiers.map(t=>`<div class="mini-row"><span><strong>${esc(t.display_name)} · ${n(Number(t.annual_roi_rate)*100,2)}%</strong><small>${n(t.minimum,2)} — ${n(t.maximum,2)} USDT · Referral ${n(Number(t.referral_rate)*100,2)}%</small></span><button class="small-button" data-tier-edit="${t.code}">Edit</button></div>`).join("")}catch(e){alert(e.message)}}
  async function review(type,id,approve){const p={approve,note:prompt(`Optional ${approve?"approval":"rejection"} note:`)||undefined};if(type==="withdrawal"&&approve){p.external_tx_hash=prompt("Enter the verified external transaction hash:");if(!p.external_tx_hash)return toast("An external transaction hash is required.","error")}try{await api(`/admin/${type}s/${id}/review`,{method:"POST",body:JSON.stringify(p)});toast(`${type[0].toUpperCase()+type.slice(1)} reviewed.`);await refresh()}catch(e){toast(e.message,"error")}}
  async function addWallet(ev){ev.preventDefault();try{await api("/admin/receiving-wallets",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(ev.currentTarget)))});ev.currentTarget.reset();toast("Public receiving wallet added.");await refresh()}catch(e){toast(e.message,"error")}}
  async function disable(id){if(!confirm("Disable this receiving address?"))return;try{await api(`/admin/receiving-wallets/${id}/disable`,{method:"POST"});toast("Receiving wallet disabled.");await refresh()}catch(e){toast(e.message,"error")}}
  async function edit(code){const t=S.tiers.find(x=>x.code===code),roi_=prompt("Annual ROI rate as a decimal (0.075 is 7.5%):",t.annual_roi_rate);if(roi_===null)return;const referral=prompt("Referral rate as a decimal (0.02 is 2%):",t.referral_rate);if(referral===null)return;try{await api(`/admin/tiers/${code}`,{method:"PATCH",body:JSON.stringify({annual_roi_rate:roi_,referral_rate:referral})});toast(`${t.display_name} updated for future positions.`);await refresh()}catch(e){toast(e.message,"error")}}
  function view(v){if(v==="admin"&&S.user?.role!=="admin")return;$$(".view").forEach(x=>x.classList.toggle("active",x.id===`view-${v}`));$$(".nav-item[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===v));const labels={dashboard:["Portfolio","Your overview"],invest:["Growth planner","Explore a position"],wallet:["Wallet","Transfers & balances"],activity:["Activity","Your ledger"],admin:["Administrator","Control center"]}[v];$("#view-kicker").textContent=labels[0];$("#view-title").textContent=labels[1];$(".sidebar").classList.remove("open");if(v==="activity")activity()}
  document.addEventListener("click",ev=>{const b=ev.target.closest("button,[data-view]");if(!b)return;if(b.dataset.action==="open-auth")authOpen(b.dataset.authMode||"login");if(b.dataset.action==="close-auth")$("#auth-dialog").close();if(b.dataset.action==="toggle-menu")$(".sidebar").classList.toggle("open");if(b.dataset.action==="copy-referral")navigator.clipboard?.writeText(S.user?.referral_code||"").then(()=>toast("Referral code copied."));if(b.dataset.explore)S.token?(view("invest"),$("#roi-tier").value=b.dataset.explore,$("#roi-amount").focus()):authOpen("register");if(b.dataset.view)view(b.dataset.view);if(b.dataset.settle)settle(b.dataset.settle);if(b.dataset.review){const[t,id,a]=b.dataset.review.split("|");review(t,id,a==="yes")}if(b.dataset.disable)disable(b.dataset.disable);if(b.dataset.tierEdit)edit(b.dataset.tierEdit)});
  $$("[data-auth-tab]").forEach(x=>x.addEventListener("click",()=>authTab(x.dataset.authTab)));$("#login-form").addEventListener("submit",e=>auth(e,false));$("#register-form").addEventListener("submit",e=>auth(e,true));$("#roi-form").addEventListener("submit",roi);$("#investment-form").addEventListener("submit",invest);$("#deposit-form").addEventListener("submit",e=>submit("/deposits",e));$("#withdrawal-form").addEventListener("submit",e=>submit("/withdrawals",e,{idempotency_key:key("withdrawal")}));$("#deposit-address").addEventListener("change",address);$("#receiving-wallet-form").addEventListener("submit",addWallet);$("#refresh-data").addEventListener("click",async()=>{await refresh();toast("Dashboard refreshed.")});$("#refresh-prices").addEventListener("click",async()=>{try{await api("/admin/prices/refresh",{method:"POST"});await refresh();toast("Market snapshots refreshed.")}catch(e){toast(e.message,"error")}});$("#sign-out").addEventListener("click",signOut);publicData();if(S.token)enter();
})();
